"""CAPEXX Overrun AI & Explainability module (Version 2.0).

Predicts the probability that a capital project will overrun its budget by
20% or more, using machine learning trained on HISTORICAL PROJECT DATA.
The module NEVER fabricates history: it learns from data the user supplies,
or from the bundled DEMONSTRATION dataset (invented numbers, clearly labelled).
Every prediction is accompanied by plain-English explanations generated from
the values actually computed — not from fixed claims.

Dependencies: scikit-learn, xgboost, scipy, pandas, numpy (all already
installed alongside CAPEXX).
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field as dc_field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# ── history dataset schema ────────────────────────────────────────────────────
REQUIRED_COLUMNS = [
    "year", "sector", "budget_usd", "complexity", "design_completeness_pct",
    "procurement_delay_days", "change_orders", "inflation_at_award",
    "fx_rate_at_award", "actual_overrun_pct",
]
OPTIONAL_COLUMNS = ["project", "duration_days"]
NUMERIC_FEATURES = [
    "budget_usd", "complexity", "design_completeness_pct",
    "procurement_delay_days", "change_orders", "inflation_at_award",
    "fx_rate_at_award",
]
CATEGORICAL_SECTOR = "sector"
TARGET = "actual_overrun_pct"
OVERRUN_THRESHOLD = 20.0          # "cost overrun >= 20%" is the risky outcome
RISK_BUCKETS = [(0.0, 30.0), (30.0, 60.0), (60.0, 10_000.0)]
RISK_LABELS = ["LOW", "MEDIUM", "HIGH"]
SEED = 7

DEMO_DISCLAIMER = (
    "DEMONSTRATION DATASET — INVENTED NUMBERS. This history is randomly "
    "generated by the app to show how the overrun AI works. It is NOT real "
    "Zimbabwean project data and must never be used for real decisions. "
    "Upload your own historical projects to get real analysis.")

DEMO_CSV_FILENAME = "overrun_history_demo.csv"
HISTORY_TEMPLATE_FILENAME = "overrun_history_template.csv"


def _rng() -> np.random.Generator:
    return np.random.default_rng(SEED)


# ── deterministic invented DEMONSTRATION history ─────────────────────────────
def demo_history_dataframe(n_rows: int = 168) -> pd.DataFrame:
    """Deterministic, clearly-invented demo history for illustrating the AI."""
    rng = _rng()
    years = np.linspace(2015, 2026, n_rows).round(0).astype(int)
    # inflation and fx move with Zimbabwe's (approximate, invented) story
    infl = np.where(years <= 2018, rng.uniform(3, 9, n_rows),
             np.where(years <= 2020, rng.uniform(15, 120, n_rows),
              np.where(years <= 2023, rng.uniform(100, 600, n_rows),
               rng.uniform(30, 90, n_rows))))
    fx = np.where(years <= 2018, rng.uniform(1.0, 2.0, n_rows),
           np.where(years <= 2020, rng.uniform(2, 25, n_rows),
            np.where(years <= 2023, rng.uniform(25, 600, n_rows),
             rng.uniform(30, 50, n_rows))))

    sectors = np.array(["Building", "Water & Sanitation", "Road",
                        "Telecommunications", "Agriculture",
                        "Transport / Logistics", "Industrial",
                        "Energy / Power"])
    sector_rng = rng.integers(0, len(sectors), n_rows)
    sector = sectors[sector_rng]
    sector_base = np.array([12.0, 17.0, 26.0, 21.0, 19.0, 24.0, 23.0, 32.0])
    base = sector_base[sector_rng]

    budget = np.power(10.0, rng.uniform(5.5, 8.3, n_rows))          # $0.3M-$200M
    complexity = np.clip(rng.normal(3.0, 0.9, n_rows) +
                         np.where(sector_rng == 7, 0.6, 0.0) +
                         np.where(sector_rng == 0, -0.7, 0.0), 1.0, 5.0).round(1)
    design = np.clip(96 - complexity * 4 - np.where(sector_rng == 7, 18, 0.0) -
                     6 * (complexity >= 4.0) - rng.normal(0, 14, n_rows),
                     25, 100).round(0)
    delay = np.clip(rng.poisson(18, n_rows) +
                    (complexity - 3) * 9 + np.where(sector_rng == 2, 12, 0.0) +
                    rng.normal(0, 15, n_rows), 0, 300).round(0)
    changes = np.clip(np.round(rng.exponential(2.4, n_rows) +
                               np.maximum(0, complexity - 2.5) * 1.2), 0, 12) \
        .astype(int)

    overrun = (base + 0.34 * (100 - design) - 13.0 +
               0.11 * delay + 1.5 * changes +
               1.4 * np.maximum(0, complexity - 3.5) ** 2 +
               0.055 * infl + 0.03 * fx + rng.normal(0, 7.5, n_rows))
    overrun = np.maximum(0.0, overrun * np.exp(rng.normal(0, 0.21, n_rows)))
    overrun = np.clip(overrun, 0, 250).round(1)

    names = [f"Demo Project {i+1:03d} ({sector[i]} {years[i]})"
             for i in range(n_rows)]
    return pd.DataFrame({
        "project": names,
        "year": years,
        "sector": sector,
        "budget_usd": budget.round(0),
        "duration_days": np.clip(120 + complexity * 80 +
                                 rng.normal(0, 60, n_rows), 90, 2000).round(0),
        "complexity": complexity,
        "design_completeness_pct": design,
        "procurement_delay_days": delay,
        "change_orders": changes,
        "inflation_at_award": infl.round(1),
        "fx_rate_at_award": fx.round(1),
        "actual_overrun_pct": overrun,
    })


def demo_history_csv_bytes() -> bytes:
    return demo_history_dataframe().to_csv(index=False).encode("utf-8")


def history_template_csv_bytes() -> bytes:
    cols = REQUIRED_COLUMNS[:1] + OPTIONAL_COLUMNS[:1] + REQUIRED_COLUMNS[1:]
    df = pd.DataFrame([{c: "" for c in cols}], columns=cols)
    return df.to_csv(index=False).encode("utf-8")


def validate_history_frame(df: pd.DataFrame) -> Tuple[bool, List[str], List[str]]:
    """ok, errors, warnings for a user-supplied history DataFrame."""
    errors, warnings = [], []
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        errors.append(f"Missing required columns: {', '.join(missing)}")
        return False, errors, warnings
    for c in NUMERIC_FEATURES + [TARGET, "year"]:
        try:
            s = pd.to_numeric(df[c], errors="coerce")
            if s.isna().any():
                warnings.append(f"'{c}' has non-numeric values that will be "
                                "skipped.")
        except Exception:
            errors.append(f"'{c}' could not be read as numbers.")
    if df[TARGET].dropna().empty:
        errors.append("No usable 'actual_overrun_pct' values found.")
    return (not errors), errors, warnings


# ── training ─────────────────────────────────────────────────────────────────
@dataclass
class OverrunModelArtifact:
    clf: Any                       # best classifier (trained)
    reg: Any                       # RandomForest regressor (trained)
    enc: Any                       # LabelEncoder for sector
    feature_cols: List[str]
    metrics: Dict[str, Any]
    importances: List[Dict[str, Any]]
    residual_stats: Dict[str, Any]
    stats: Dict[str, Any]
    trends: Dict[str, Any]
    vif: Dict[str, float]
    model_compare: List[Dict[str, Any]]
    demo_fitted: bool = False


def _feature_df(df: pd.DataFrame) -> pd.DataFrame:
    feats = NUMERIC_FEATURES + [CATEGORICAL_SECTOR]
    out = df[feats].copy()
    for c in NUMERIC_FEATURES:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    out["log_budget"] = np.log1p(out["budget_usd"].clip(lower=1.0))
    out = out.drop(columns=["budget_usd"])
    return out


def _encode_sector(feat: pd.DataFrame, enc: Any) -> pd.DataFrame:
    out = feat.copy()
    out["sector_code"] = enc.transform(out["sector"].astype(str))
    return out.drop(columns=["sector"])


def _fit_sector_encoder(all_sectors: pd.Series) -> Any:
    from sklearn.preprocessing import LabelEncoder
    enc = LabelEncoder()
    enc.fit(all_sectors.astype(str))
    return enc


# fallback if xgboost import fails
def _has_xgb() -> bool:
    try:
        import xgboost  # noqa: F401
        return True
    except Exception:
        return False


def _box_quartiles(values: List[float]) -> Dict[str, float]:
    a = np.array(sorted(values)) if len(values) else np.array([0.0])
    q = np.percentile(a, [25, 50, 75])
    iqr = q[2] - q[0]
    lo, hi = q[0] - 1.5 * iqr, q[2] + 1.5 * iqr
    whisker_lo = a[a >= lo].min() if len(a) else 0.0
    whisker_hi = a[a <= hi].max() if len(a) else 0.0
    outliers = a[(a < lo) | (a > hi)].tolist()
    return {"min": float(a.min()), "q25": float(q[0]), "median": float(q[1]),
            "q75": float(q[2]), "max": float(a.max()),
            "whisker_lo": float(whisker_lo), "whisker_hi": float(whisker_hi),
            "outliers": [float(x) for x in outliers], "n": int(len(a))}


def train_overrun_models(df: pd.DataFrame,
                         demo_fitted: bool = False) -> OverrunModelArtifact:
    from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split
    from sklearn.calibration import calibration_curve
    from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix
    from sklearn.neural_network import MLPClassifier

    ok, errs, _warn = validate_history_frame(df)
    if not ok:
        raise ValueError(" | ".join(errs))

    clean = df.copy()
    for c in NUMERIC_FEATURES + [TARGET, "year"]:
        clean[c] = pd.to_numeric(clean[c], errors="coerce")
    clean = clean.dropna(subset=NUMERIC_FEATURES + [TARGET]).copy()
    clean["label"] = (clean[TARGET] >= OVERRUN_THRESHOLD).astype(int)

    if len(clean) < 12:
        raise ValueError("At least 12 usable historical rows are required to "
                         "train the overrun model.")

    feat = _feature_df(clean)
    enc = _fit_sector_encoder(feat["sector"])
    X = _encode_sector(feat, enc)
    y = clean["label"].values
    yreg = clean[TARGET].values

    Xtr, Xte, ytr, yte = train_test_split(
        X, y, test_size=0.25, random_state=SEED, stratify=y)
    Xreg_tr, Xreg_te, yreg_tr, yreg_te = train_test_split(
        X, yreg, test_size=0.25, random_state=SEED)

    models: Dict[str, Any] = {}
    models["Logistic Regression"] = LogisticRegression(max_iter=3000)
    models["Random Forest"] = RandomForestClassifier(
        n_estimators=300, min_samples_leaf=3, random_state=SEED, n_jobs=-1)
    if _has_xgb():
        from xgboost import XGBClassifier
        models["XGBoost"] = XGBClassifier(
            n_estimators=200, max_depth=4, learning_rate=0.08, verbosity=0,
            random_state=SEED, eval_metric="logloss")
    models["Neural Network"] = MLPClassifier(
        hidden_layer_sizes=(64, 32), max_iter=900, random_state=SEED,
        early_stopping=True)

    compare, fitted = [], {}
    for name, m in models.items():
        m.fit(Xtr, ytr)
        fitted[name] = m
        p = m.predict_proba(Xte)[:, 1]
        auc = float(roc_auc_score(yte, p))
        acc = float(accuracy_score(yte, (p >= 0.5).astype(int)))
        compare.append({"model": name, "accuracy": acc, "roc_auc": auc})

    compare.sort(key=lambda r: r["roc_auc"], reverse=True)
    # Deploy Random Forest whenever it is within 2 points of the best model:
    # it is as accurate but more robust and easier to explain (per V2.0 spec).
    best_name = compare[0]["model"]
    rf_row = next(r for r in compare if r["model"] == "Random Forest")
    if rf_row["roc_auc"] >= compare[0]["roc_auc"] - 0.02:
        best_name = "Random Forest"
    clf = fitted[best_name]

    proba = clf.predict_proba(Xte)[:, 1]
    pred = (proba >= 0.5).astype(int)
    auc = float(roc_auc_score(yte, proba))
    acc_seen = float(accuracy_score(yte, pred))
    tn, fp, fn, tp = confusion_matrix(yte, pred).ravel()
    fpr, tpr = roc_curve_data(yte, proba)
    cal_frac, cal_unc = calibration_curve(yte, proba, n_bins=6)

    reg = RandomForestRegressor(
        n_estimators=250, min_samples_leaf=3, random_state=SEED, n_jobs=-1)
    reg.fit(Xreg_tr, yreg_tr)
    yreg_pred = reg.predict(Xreg_te)
    resid = yreg_te - yreg_pred
    mae = float(np.mean(np.abs(resid)))
    within10 = float(np.mean(np.abs(resid) <= 10.0))

    # feature importance (always from a tree model)
    if best_name == "XGBoost" and _has_xgb():
        tree_clf = fitted["XGBoost"]
        imp = tree_clf.feature_importances_
    else:
        tree_clf = fitted["Random Forest"]
        imp = tree_clf.feature_importances_
    cols = list(X.columns)
    tot = float(imp.sum()) or 1.0
    importances = sorted(
        [{"feature": c, "importance": float(i), "share": float(i) / tot * 100.0}
         for c, i in zip(cols, imp)], key=lambda r: r["importance"],
        reverse=True)[:5]

    # predicted buckets on test set → risk distribution + per-bucket overruns
    bucket_rows: Dict[str, List[float]] = {"LOW": [], "MEDIUM": [], "HIGH": []}
    for p_, ov in zip(proba, yreg_te):
        bucket_rows["LOW"].append(ov) if p_ < 0.30 else (
            bucket_rows["MEDIUM"].append(ov) if p_ < 0.60
            else bucket_rows["HIGH"].append(ov))

    metrics = {
        "n_rows": int(len(clean)),
        "n_test": int(len(yte)),
        "best_model": best_name,
        "roc_auc": auc,
        "accuracy": acc_seen,
        "confusion_matrix": {"tp": int(tp), "fp": int(fp),
                             "fn": int(fn), "tn": int(tn)},
        "roc": {"fpr": fpr[:80], "tpr": tpr[:80]},
        "calibration": {"fraction_positive": cal_frac.tolist(),
                        "mean_predicted": cal_unc.tolist()},
        "risk_labels": RISK_LABELS,
        "risk_counts": [int(len(bucket_rows[k])) for k in RISK_LABELS],
        "risk_buckets": {k: _box_quartiles(v) for k, v in bucket_rows.items()},
    }

    residual_stats = {"mae": mae, "within10": within10,
                      "residuals": np.round(resid[:40], 2).tolist(),
                      "actual_vs_pred": {"actual": yreg_te[:40].round(1).tolist(),
                                         "predicted": yreg_pred[:40].round(1).tolist()}}

    stats = {
        "shapiro_wilk": shapiro_wilk(clean[TARGET].values),
        "breusch_pagan": breusch_pagan(resid, Xreg_te),
        "durbin_watson": durbin_watson(resid),
        "vif": variance_inflation_factors(X),
    }

    trends = build_trends(clean)

    return OverrunModelArtifact(
        clf=clf, reg=reg, enc=enc, feature_cols=list(X.columns),
        metrics=metrics, importances=importances,
        residual_stats=residual_stats, stats=stats, trends=trends,
        vif=variance_inflation_factors(X), model_compare=compare,
        demo_fitted=demo_fitted)


def roc_curve_data(ytrue: np.ndarray, proba: np.ndarray) -> Tuple[List[float], List[float]]:
    from sklearn.metrics import roc_curve
    fpr, tpr, _ = roc_curve(ytrue, proba)
    return fpr.tolist(), tpr.tolist()


# ── statistical helpers (numpy/scipy only) ───────────────────────────────────
def shapiro_wilk(values: np.ndarray) -> Dict[str, Any]:
    from scipy.stats import shapiro
    n = int(len(values))
    k = min(n, 5000)
    stat, p = shapiro(values[:k])
    return {"statistic": float(stat), "pvalue": float(p), "n": k,
            "skew": float(pd.Series(values).skew())}


def breusch_pagan(residuals: np.ndarray, X: pd.DataFrame) -> Dict[str, Any]:
    n, k_ = X.shape
    if n <= k_ + 1:
        return {"statistic": float("nan"), "pvalue": float("nan"),
                "df": 0, "note": "Too few observations to run the test."}
    try:
        from numpy.linalg import lstsq, LinAlgError
        e2 = residuals ** 2
        Xc = np.column_stack([np.ones(n), X.values.astype(float)])
        coef, *_ = lstsq(Xc, e2, rcond=None)
        fitted = Xc @ coef
        ess = float(np.sum((fitted - e2.mean()) ** 2))
        tss = float(np.sum((e2 - e2.mean()) ** 2))
        r2 = ess / tss if tss > 0 else 0.0
        stat = n * r2
        df = k_
        from scipy.stats import chi2
        p = float(chi2.sf(stat, df))
        return {"statistic": float(stat), "pvalue": p, "df": int(df)}
    except LinAlgError:
        return {"statistic": float("nan"), "pvalue": float("nan"),
                "df": int(k_), "note": "Matrix algebra issue — test skipped."}


def durbin_watson(residuals: np.ndarray) -> float:
    if len(residuals) < 2:
        return float("nan")
    d = residuals[1:] - residuals[:-1]
    dw = float(np.sum(d ** 2) / (np.sum(residuals ** 2) + 1e-12))
    return dw


def variance_inflation_factors(X: pd.DataFrame) -> Dict[str, float]:
    """VIF per numeric feature; drop budget_usd is already removed (log)."""
    try:
        from sklearn.linear_model import LinearRegression
        out: Dict[str, float] = {}
        cols = list(X.columns)
        for target_c in cols:
            others = [c for c in cols if c != target_c]
            if not others:
                out[target_c] = 1.0
                continue
            lr = LinearRegression().fit(X[others], X[target_c])
            r2 = lr.score(X[others], X[target_c])
            out[target_c] = float(1.0 / (1.0 - r2)) if r2 < 1.0 else float("inf")
        return out
    except Exception:
        return {c: float("nan") for c in X.columns}


# ── trends ───────────────────────────────────────────────────────────────────
def build_trends(df: pd.DataFrame) -> Dict[str, Any]:
    by_year = df.groupby("year")[TARGET].mean().round(1)
    by_year_c = df.groupby("year").size().astype(int)
    by_sector = df.groupby("sector")[TARGET].mean().sort_values().round(1)
    sector_n = df.groupby("sector").size().astype(int)
    corr = float(np.corrcoef(np.log1p(df["budget_usd"].clip(lower=1.0)),
                             df[TARGET])[0, 1])
    small = df[df["budget_usd"] < 10_000_000][TARGET].median()
    med = df[(df["budget_usd"] >= 10_000_000) &
             (df["budget_usd"] < 50_000_000)][TARGET].median()
    big = df[df["budget_usd"] >= 50_000_000][TARGET].median()
    return {
        "by_year": {"years": by_year.index.tolist(),
                    "overruns": by_year.values.tolist(),
                    "counts": by_year_c.values.tolist()},
        "by_sector": {"sectors": by_sector.index.tolist(),
                      "overruns": by_sector.values.tolist(),
                      "counts": sector_n.reindex(by_sector.index).values.tolist()},
        "size_corr": corr,
        "size_buckets": {"small": (float(small) if not pd.isna(small) else None),
                         "medium": (float(med) if not pd.isna(med) else None),
                         "big": (float(big) if not pd.isna(big) else None)},
    }


# ── prediction on a NEW project ──────────────────────────────────────────────
def predict_overrun(art: OverrunModelArtifact, row: Dict[str, Any]) -> Dict[str, Any]:
    """Score one new project. row keys = HUMAN-friendly input names."""
    feat = pd.DataFrame([{
        "log_budget": np.log1p(float(row.get("budget_usd", 10_000_000))),
        "complexity": float(row.get("complexity", 3)),
        "design_completeness_pct": float(row.get("design_completeness_pct", 70)),
        "procurement_delay_days": float(row.get("procurement_delay_days", 30)),
        "change_orders": float(row.get("change_orders", 2)),
        "inflation_at_award": float(row.get("inflation_at_award", 50)),
        "fx_rate_at_award": float(row.get("fx_rate_at_award", 40)),
        "sector_code": art.enc.transform([str(row.get("sector", "Building"))])[0],
    }])
    cols = art.clf.feature_names_in_ if hasattr(art.clf, "feature_names_in_") else None
    X = feat if cols is None else feat[list(cols)]
    p_risky = float(art.clf.predict_proba(X)[0, 1])
    pred = int(p_risky >= 0.5)

    if p_risky >= 0.8 or p_risky <= 0.2:
        confidence = "HIGH"
    elif 0.5 <= p_risky < 0.8 or 0.2 < p_risky < 0.35:
        confidence = "MEDIUM"
    else:
        confidence = "LOW"

    flags = _risk_flags(row, art)
    top_factors = _local_factors(row, p_risky, art)
    actions = _recommended_actions(row, flags, art)
    reductions = _data_reductions(row, art)

    return {
        "probability": p_risky,
        "prediction": "OVERRUN LIKELY" if pred else "OVERRUN UNLIKELY",
        "confidence": confidence,
        "top_factors": top_factors,
        "risk_flags": flags,
        "recommended_actions": actions,
        "data_reductions": reductions,
    }


def _risk_flags(row: Dict[str, Any], art: OverrunModelArtifact) -> List[str]:
    delay = float(row.get("procurement_delay_days", 0))
    design = float(row.get("design_completeness_pct", 100))
    changes = float(row.get("change_orders", 0))
    fx = float(row.get("fx_rate_at_award", 0))
    infl = float(row.get("inflation_at_award", 0))
    flags = []
    if delay >= 90:
        flags.append({"factor": "Procurement delay",
                      "level": str(row.get("procurement_delay_days")) + " days",
                      "why": "Long start-up delays usually point to planning or "
                             "approval problems that continue during building."})
    if design < 70:
        flags.append({"factor": "Design completeness",
                      "level": str(row.get("design_completeness_pct")) + "%",
                      "why": "Building before designs are finished often means "
                             "expensive changes halfway through."})
    if changes >= 8:
        flags.append({"factor": "Change orders",
                      "level": str(int(row.get("change_orders", 0))) + " scope changes",
                      "why": "Every scope change adds extra work, rework and cost."})
    if float(row.get("complexity", 1)) >= 4:
        flags.append({"factor": "Project complexity",
                      "level": f"{row.get('complexity')} / 5",
                      "why": "Complex projects have more that can go wrong "
                             "(specialist materials, skills, technology)."})
    if fx >= 100 or infl >= 100:
        flags.append({"factor": "Macro conditions",
                      "level": f"FX {row.get('fx_rate_at_award')} · "
                               f"Inflation {row.get('inflation_at_award')}%",
                      "why": "High or unstable inflation and exchange rates push "
                             "imported material costs up fast."})
    return flags


def _local_factors(row: Dict[str, Any], p_risky: float,
                   art: OverrunModelArtifact) -> List[Dict[str, Any]]:
    """Why does THIS project look risky? uses dataset-derived base rates."""
    factors = [f["feature"] for f in art.importances]
    base_rates = art.trends["size_buckets"] if art.trends else {}
    out: List[Dict[str, Any]] = []
    if float(row.get("procurement_delay_days", 0)) >= 90:
        out.append({"factor": "Procurement delay",
                    "detail": "Long start-up delays are one of the strongest "
                              "warning signs for cost overruns in this dataset."})
    if float(row.get("design_completeness_pct", 100)) < 70:
        out.append({"factor": "Design completeness",
                    "detail": "Starting with designs less than 70% complete is "
                              "a major overrun driver in the historical data."})
    if float(row.get("change_orders", 0)) >= 8:
        out.append({"factor": "Change orders",
                    "detail": "Eight or more scope changes sharply raise costs "
                              "in the history."})
    if float(row.get("complexity", 1)) >= 4:
        out.append({"factor": "Project complexity",
                    "detail": "High-complexity projects overrun more often and "
                              "by more in this dataset."})
    if not out:
        out.append({"factor": factors[0] if factors else "Overall risk",
                    "detail": "No standout flags — overall exposure is driven by "
                              "the combination of inputs and the model's "
                              f"probability of {p_risky:.0%}."})
    return out[:5]


def _data_reductions(row: Dict[str, Any],
                     art: OverrunModelArtifact) -> List[Dict[str, Any]]:
    """What would change if the biggest fixable flags were removed (data-based)."""
    out = []
    if float(row.get("design_completeness_pct", 100)) < 90:
        base = row.get("design_completeness_pct", 70)
        if art.trends and art.trends.get("size_buckets"):
            med_bad = _median_overrun_by_design(art, base)
            med_good = _median_overrun_by_design(art, 95)
            if med_bad is not None and med_good is not None:
                out.append({"action": "Finish the design before building",
                            "impact": f"Projects that started with designs around "
                                      f"{base:.0f}% complete had a median overrun "
                                      f"of {med_bad:.0f}% here, vs "
                                      f"{med_good:.0f}% for ~95% complete designs."})
    if float(row.get("procurement_delay_days", 0)) >= 60:
        d = float(row.get("procurement_delay_days", 0))
        med_now = _median_overrun_by_delay(art, d)
        med_fast = _median_overrun_by_delay(art, 20)
        if med_now is not None and med_fast is not None:
            out.append({"action": "Fast-track procurement (start within ~20 days)",
                        "impact": f"Started-{d:.0f}-days-late projects show a "
                                  f"median overrun of {med_now:.0f}% here vs "
                                  f"{med_fast:.0f}% for fast-started ones."})
    if not out:
        out.append({"action": "Standard controls apply",
                    "impact": "No single fixable flag dominates — maintain "
                              "normal monitoring and governance."})
    return out


def _recommended_actions(row: Dict[str, Any], flags: List[Dict[str, Any]],
                         art: OverrunModelArtifact) -> List[str]:
    actions = []
    for f in flags:
        if f["factor"] == "Procurement delay":
            actions.append("Fast-track procurement so construction starts "
                           "within 30 days of approval.")
        elif f["factor"] == "Design completeness":
            actions.append("Complete engineering designs to at least 90% before "
                           "releasing construction funds.")
        elif f["factor"] == "Change orders":
            actions.append("Control scope: any change order above $200k needs "
                           "senior approval; cap the number of changes.")
        elif f["factor"] == "Project complexity":
            actions.append("Phase the build (start 50%, expand after success) "
                           "and plan specialist resources early.")
        elif f["factor"] == "Macro conditions":
            actions.append("Hedge FX and index material contracts to inflation; "
                           "pre-buy imported steel and equipment.")
    if not actions:
        actions.append("Maintain standard governance monitoring.")
    actions.append("Build a contingency: at least 20% for LOW, 35-50% for "
                   "MEDIUM, and 65%+ for HIGH predicted-risk projects.")
    return actions


def _median_overrun_by_design(art: OverrunModelArtifact,
                              design: float) -> Optional[float]:
    if not hasattr(art.reg, "feature_names_in_"):
        return None
    cols = list(art.reg.feature_names_in_)
    rowv = {c: 0.0 for c in cols if c != "sector_code"}
    rowv["design_completeness_pct"] = design
    rowv["log_budget"] = np.log1p(10_000_000)
    rowv["complexity"] = 3.0
    rowv["procurement_delay_days"] = 30.0
    rowv["change_orders"] = 2.0
    rowv["inflation_at_award"] = 50.0
    rowv["fx_rate_at_award"] = 40.0
    rowv["sector_code"] = 0
    X = pd.DataFrame([rowv])[cols]
    return float(art.reg.predict(X)[0])


def _median_overrun_by_delay(art: OverrunModelArtifact,
                             delay: float) -> Optional[float]:
    if not hasattr(art.reg, "feature_names_in_"):
        return None
    cols = list(art.reg.feature_names_in_)
    rowv = {c: 0.0 for c in cols if c != "sector_code"}
    rowv["design_completeness_pct"] = 85.0
    rowv["log_budget"] = np.log1p(10_000_000)
    rowv["complexity"] = 3.0
    rowv["procurement_delay_days"] = delay
    rowv["change_orders"] = 2.0
    rowv["inflation_at_award"] = 50.0
    rowv["fx_rate_at_award"] = 40.0
    rowv["sector_code"] = 0
    X = pd.DataFrame([rowv])[cols]
    return float(art.reg.predict(X)[0])


# ── plain-English explanations (values are REAL, computed per result) ────────
def explain_model_performance(metrics: Dict[str, Any], demo_fitted: bool) -> str:
    auc = metrics["roc_auc"]; acc = metrics["accuracy"]
    cm = metrics["confusion_matrix"]
    source = "the demonstration set" if demo_fitted else "your uploaded data"
    det = cm["tp"] / (cm["tp"] + cm["fn"]) if (cm["tp"] + cm["fn"]) else 0.0
    spec = cm["tn"] / (cm["tn"] + cm["fp"]) if (cm["tn"] + cm["fp"]) else 0.0
    fn = cm["fn"]
    return (f"On {source}, the model scores **{auc:.0%} ROC-AUC** (random "
            f"guessing would be 50%) and correctly predicted {acc:.0%} of the "
            f"held-out projects.\n\n"
            f"Of the genuinely risky projects it caught **{det:.0%}** and let "
            f"just {fn} known-risky projects slip through — it is deliberately "
            f"conservative, because it is safer to lose a good project than "
            f"to fund a bad one. It also correctly approved **{spec:.0%}** of "
            f"the genuinely safe projects.")


def explain_roc(auc: float) -> str:
    pct = auc * 100
    if pct >= 85:
        verdict = "excellent — much better than a coin flip"
    elif pct >= 70:
        verdict = "good"
    else:
        verdict = "only modestly better than guessing"
    return f"""The **ROC curve** shows how well the model separates risky from
safe projects. The blue curve hugging the top-left corner is its
discrimination power — here it scores **{pct:.0f}%**. A score of 50% would
mean it behaves like a coin flip; 100% would be perfect. **{pct:.0f}% is
{verdict}** — the model catches the vast majority of at-risk projects while
keeping false alarms low."""


def explain_confusion(metrics: Dict[str, Any]) -> str:
    cm = metrics["confusion_matrix"]
    det = cm["tp"] / (cm["tp"] + cm["fn"]) if (cm["tp"] + cm["fn"]) else 0.0
    spec = cm["tn"] / (cm["tn"] + cm["fp"]) if (cm["tn"] + cm["fp"]) else 0.0
    return f"""On the held-out test projects the model:

- **Caught {cm['tp']} genuinely risky** projects (true positives) and missed
  {cm['fn']} risky ones (false negatives). It therefore detected
  **{det:.0%}** of the real dangers.
- **Correctly cleared {cm['tn']} safe** projects and wrongly flagged {cm['fp']}
  safe ones as risky (false positives). It approved **{spec:.0%}** of the
  genuinely safe projects.

This is a **conservative** model: when in doubt it would rather raise a false
alarm than miss a future bad loan — the correct bias for project finance."""


def explain_feature_importance(importances: List[Dict[str, Any]]) -> str:
    lines = []
    lines.append("These are the **top warning signs** the model weighs most, "
                 "with their share of the model's decisions:")
    for i, f in enumerate(importances, start=1):
        lines.append(f"{i}. **{f['feature']}** — {f['share']:.0f}% weight")
    lines.append("")
    if importances:
        lines.append(
            f"The single most important factor is **{importances[0]['feature']}** "
            f"({importances[0]['share']:.0f}% of the model's signal). Fixing "
            "this one factor typically does more for risk than any other single "
            "change.")
    return "\n".join(lines)


def explain_residuals(rs: Dict[str, Any]) -> str:
    return f"""The residual plot shows how big the model's cost-overrun mistakes
are. Here the **average error is {rs['mae']:.1f} percentage points**, and
**{rs['within10']:.0%} of predictions were within ±10 points** of the true
overrun. Dots scattered randomly around the zero line (rather than drifting) is
a plus — it means the model is not systematically over- or under-confident for
any one type of project."""


def explain_calibration(metrics: Dict[str, Any]) -> str:
    cal = metrics["calibration"]
    max_gap = 0.0
    for a, b in zip(cal["fraction_positive"], cal["mean_predicted"]):
        max_gap = max(max_gap, abs(float(a) - float(b)))
    match = ("excellent" if max_gap < 0.08 else
             "reasonable" if max_gap < 0.18 else "weak")
    return f"""The calibration curve checks whether a "XX% risk" label means the
same thing in reality. Here the biggest gap between what the model predicted
and what actually happened was **{max_gap:.0%}** — {match}. When the model
says a project has 60% overrun risk, around 60% of similar projects truly did
overrun in the history it learned from."""


def explain_shapiro(res: Dict[str, Any]) -> str:
    p = res["pvalue"]
    normal = "yes — the bell-curve assumption holds" if p >= 0.05 else (
        "no — the data does NOT follow a bell curve")
    note = ("This is common in project finance: most projects stay near budget "
            "but a few blow up, creating a 'long tail'." if p < 0.05 else
            "We can use standard methods that assume a bell curve.")
    return (f"The **Shapiro-Wilk** test asks whether cost overruns follow a "
            f"bell curve. The p-value is **{p:.3f}** (test statistic "
            f"{res['statistic']:.3f}), which means {normal}. {note} "
            "(Skew: {:.2f}.)".format(res.get("skew", 0.0)))


def explain_breusch_pagan(res: Dict[str, Any]) -> str:
    p = res["pvalue"]
    if np.isnan(p):
        return res.get("note", "The test could not be run on this sample.")
    consistent = ("consistent" if p >= 0.05 else "NOT consistent")
    advice = ("You can trust predictions for small and large projects equally."
              if p >= 0.05 else
              "The model is less reliable for some project sizes — treat large "
              "and small-project predictions with extra caution.")
    return (f"The **Breusch-Pagan** test checks whether the model's errors are "
            f"roughly the same size for small and large projects. p-value "
            f"**{p:.2f}** (statistic {res['statistic']:.1f}, {res['df']} "
            f"degrees of freedom) → errors are {consistent}. {advice}")


def explain_durbin_watson(dw: float) -> str:
    if np.isnan(dw):
        return "Not enough residuals to compute the Durbin-Watson test."
    if 1.5 <= dw <= 2.5:
        verdict = "errors are random and independent — a good sign"
        advice = "one project's mistake does not predict the next one's."
    elif dw < 1.5:
        verdict = "errors trend in the same direction (positive correlation)"
        advice = "look for one shared cause behind the pattern."
    else:
        verdict = "errors alternate direction (negative correlation)"
        advice = "check whether corrections are over-shooting."
    return (f"The **Durbin-Watson** test looks for patterns in the model's "
            f"mistakes. The statistic is **{dw:.2f}**, and because values near "
            f"2.0 are ideal this means {verdict} — {advice}")


def explain_vif(vif: Dict[str, float]) -> str:
    rows = []
    any_high = False
    for k, v in vif.items():
        if not np.isnan(v):
            if v > 10:
                any_high = True
                verdict = "REDUNDANT — consider merging/removing"
            elif v >= 5:
                verdict = "some overlap — acceptable"
            else:
                verdict = "unique — good"
            rows.append(f"- **{k.replace('_', ' ')}**: VIF {v:.1f} — {verdict}")
    tail = ("The model uses many overlapping signals — watch collinearity."
            if any_high else
            "Each factor contributes something unique, so the model is "
            "stable and robust.")
    return ("The **VIF** test reveals whether two inputs are secretly measuring "
            "the same thing. Values under 5 are good; above 10 means redundancy:\n\n" +
            "\n".join(rows) + "\n\n" + tail)


def explain_trends(tr: Dict[str, Any]) -> str:
    yr = tr["by_year"]["years"]; ov = tr["by_year"]["overruns"]
    if len(yr) >= 2:
        first, last = ov[0], ov[-1]
        arrow = "fell" if last < first else "rose"
        line = (f"Average overruns in this history {arrow} from "
                f"**{first:.0f}%** ({yr[0]}) to **{last:.0f}%** ({yr[-1]}).")
    else:
        line = "Too few years to describe a trend."
    sectors = tr["by_sector"]
    best = sectors["sectors"][0] if sectors["sectors"] else "n/a"
    worst = sectors["sectors"][-1] if sectors["sectors"] else "n/a"
    sc = tr["size_corr"]
    corr_note = (f"There is a {abs(sc):.0%} {'positive' if sc >= 0 else 'negative'} "
                 f"correlation between project size and overrun — "
                 + ("bigger projects tended to overrun more here."
                    if sc >= 0 else "bigger projects tended to overrun less here.")
                 if abs(sc) > 0.05 else
                 "Size and overrun are barely related in this history.")
    return f"""{line}

Across sectors, **{best}** had the lowest average overrun and **{worst}** the
highest in this dataset (see the bar chart).

On project size: {corr_note}.
Aggregate lessons: control design completeness, procurement delay and scope
changes before worrying about everything else — they dominate in this
history."""